### PR TITLE
:see_no_evil: git-ignore common Python development files

### PR DESCRIPTION
**Pull request by kurtmckee**
This addresses a significant number of unignored files generated by running pytest locally.

So far, I've been unable to run pipgrip on Windows (it crashes for multiple reasons), so I'm working to resolve an existing test suite failure before attempting to resolve the crashes I'm seeing.

### CODE REVIEW

**Comment by kurtmckee** [comment]
> ❗ Your organization needs to install the [Codecov GitHub app](https://github.com/apps/codecov/installations/select_target) to enable full functionality.

Calling out that this notification appears in all Codecov messages.

**Comment by ddelange** [comment]
Hey @kurtmckee 👋 

I'll close this one in favour of a user-wide `~/.gitignore`:
```
curl -sLw "\n" "http://gitignore.io/api/macos,python,django,sublimetext" >> ~/.gitignore
```

For all possibilities, see http://gitignore.io/api/list.

That should cover each developer's personal favourite editor / python setup / dev environment and they can forget about it forever!

**Comment by ddelange** [comment]
> > ❗ Your organization needs to install the [Codecov GitHub app](https://github.com/apps/codecov/installations/select_target) to enable full functionality.
> 
> Calling out that this notification appears in all Codecov messages.

Thanks, fixed!

**Comment by ddelange** [comment]
added `git config --global core.excludesfile "~/.gitignore"` in the comment above

**Comment by kurtmckee** [comment]
I use a global gitignore for both Linux and Windows to cover my own editor files and virtual environment directories and so forth, but I recommend including language-specific ignores in-repo so that incoming developers don't have to wrangle with an already-complicated.

I hope you'll reconsider including these Python language- and tool-specific ignores.

**Comment by ddelange** [comment]
fair enough! your argument outweighs the sake of deduplication :)

**Comment by kurtmckee** [comment]
Thank you for reconsidering! 🙏👍

**Pull request merged**
