### PR TITLE
:loud_sound: Add error logging with partial tree when a call to pip fails

### LINKED ISSUE #65: Show partial tree on errors
Need `pipgrip` to render partial tree when installation fails with errors. 

#### Use case / motivation

I need to see who pulls in broken dependency when CI jobs fail.

#### Related Issues

The discussion started here https://github.com/ddelange/pipgrip/issues/52#issuecomment-794050929

And the solution I used was to pipe `requirements.txt` line by line until `pipgrip` fails.
```
cat requirements.txt | xargs -n 1 pipgrip --tree -v
```
However, for [this failure](https://github.com/kvesteri/sqlalchemy-utils/runs/3878543792) the dependencies are specified as `.[test_all]` in `tox.ini` and configured dynamically in `setup.py`.

The `cat` also won't work well for deeper levels in hierarchy.

### PR DESCRIPTION
**Pull request by ddelange**
Shows a partial tree (marked with `failed`/`scheduled` for incomplete leaves) in case `pipgrip.pipper` fails to provide a wheel for a dependency in the tree. No tree is rendered if one of the root dependencies (from the pipgrip command) fails.

Closes #65, closes #66

Example: on python 3.8, adding an impossible `tensorflow<2` to pipgrip's requirements and running on itself results in:
```console
$ pipgrip .
ERROR: Downloading/building wheel for tensorflow<2 failed with output:
ERROR: Could not find a version that satisfies the requirement tensorflow<2 (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.7.0rc0)
ERROR: No matching distribution found for tensorflow<2
ERROR: Failed to download/build wheel for tensorflow<2. Best guess PartialSolution tree after the last solving decision (Package("."), <Version 0.6.11.dev1+dirty>):
. (0.6.11.dev1+dirty)
├── anytree (?)
├── click>=7 (?)
├── packaging>=17 (?)
├── pip>=7.1.0 (?)
├── pkginfo>=1.4.2 (?)
├── setuptools>=38.3 (?)
├── tensorflow<2 (?)
└── wheel (?)
Error: Failed to download/build wheel for tensorflow<2
```

Note the `last_decision` discussed in #65 at the end of the last `ERROR:` statement in the output

### CODE REVIEW

**Comment by ddelange** [comment]
Thanks for the input, makes sense!

- scheduled: done - any package with missing data, which is not the culprit, is automatically in 'scheduled' state
- done1: will be a genuine leaf in the tree like always
- done2: will be completely visualised as far as possible
- failed: the culprit will now show `failed` instead of `?`

```console
$ pipgrip .
ERROR: Downloading/building wheel for tensorflow<2 failed with output:
ERROR: Could not find a version that satisfies the requirement tensorflow<2 (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.7.0rc0)
ERROR: No matching distribution found for tensorflow<2
ERROR: Failed to download/build wheel for tensorflow<2. Best guess PartialSolution tree after the last solving decision (Package("."), <Version 0.6.11.dev1+dirty>):
. (0.6.11.dev1+dirty)
├── anytree (scheduled)
├── click>=7 (scheduled)
├── packaging>=17 (scheduled)
├── pip>=7.1.0 (scheduled)
├── pkginfo>=1.4.2 (scheduled)
├── setuptools>=38.3 (scheduled)
├── tensorflow<2 (failed)
└── wheel (scheduled)
Error: Failed to download/build wheel for tensorflow<2
```

**Comment by ddelange** [comment]
> Like after "INFO: discovering sqlalchemy>=1.0" should there be already a metadata about children dependencies

The dependencies of this succeeded build are stored in `source.packages`, however the `solver` from which this tree is built has no decision on this package yet: no version pin has been chosen and so no data available in the PartialSolution tree. This is because the solver discovers and populates the 'database' first (lazily), and then chooses which package to make the next decision on using that data: https://github.com/ddelange/pipgrip/blob/0.6.11/src/pipgrip/libs/mixology/version_solver.py#L337

**Comment by abitrolly** [comment]
Awesome. )

So it is a [breadth first search](https://en.wikipedia.org/wiki/Breadth-first_search) with a fast failure.

Anyways that's already works for me. Out of curiosity, it is possible to kick the `solver` to visit the good leafs even if some package failed to resolve `(scheduled)` status?

**Comment by ddelange** [comment]
Sounds like a cool idea :)

`solver` could callback and perform `build_tree` with the current `solver.solution` each time the tree changes. 

I think a callback after each mutation of the `solver.solution._decisions` dict _should_ do the trick
https://github.com/ddelange/pipgrip/blob/0.6.11/src/pipgrip/libs/mixology/partial_solution.py#L120 

A cool OrderedDict subclass with callback or so?

**Comment by abitrolly** [comment]
https://github.com/ddelange/pipgrip/blob/e578a978674a17b6c723193ffb5dc31f63e7091f/src/pipgrip/cli.py#L145-L151

I would say `build_tree` belong to resolver, not cli. Or to renderer, if the interface of solver results can be clearly defined. The interface that could come handy to compare different resolvers, like https://github.com/FFY00/python-resolver

**Comment by ddelange** [comment]
Nevermind callback and OrderedDict.

If there is a running history of `solver.solution.decisions` at every mutation, the only additional data needed to visualise the trees' evolution is `source`. These together can be fed into `build_tree` any time :)

**Pull request merged**
